### ISSUE TITLE
Reflect.json is not generating.

### ISSUE THREAD

**Issue by sureshg** [graemerocher/micronaut-graal-experiments#1]
Tried running the app as mentioned in the README, but reflect.json is not genearting under build dir.

```$ java -jar build/libs/hello-world-java-0.1-all.jar
02:11:42.831 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 858ms. Server Running: http://localhost:8080
^C02:12:49.216 [Thread-2] INFO  io.micronaut.runtime.Micronaut - Embedded Application shutting down
```

**Comment by jonbettinger** [comment]
> but reflect.json is genearting under build dir.

That's a typo - the reflect.json file is **not** generating at all.

**Comment by sureshg** [comment]
@jonbettinger thanks , corrected it.

**Comment by jonbettinger** [comment]
Looking at [GraalClassLoadingReporter](https://github.com/micronaut-projects/micronaut-core/blob/master/graal/src/main/java/io/micronaut/graal/reflect/GraalClassLoadingReporter.java), it seems that a System property graal.class.analysis is being checked to enable the reflect.json generator. So I tried `java -Dgraal.class.analysis=true -jar build/libs/hello-world-java-0.1-all.jar`  but get
```
Uncaught exception at /scratch/graaluser/buildslave/e/main/graal-jvmci-8/src/share/vm/jvmci/jvmciCompiler.cpp:125
java.lang.ExceptionInInitializerError
        at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.onSelection(HotSpotGraalCompilerFactory.java:74)
        at jdk.vm.ci.hotspot.HotSpotJVMCICompilerConfig.getCompilerFactory(HotSpotJVMCICompilerConfig.java:128)
        at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.<init>(HotSpotJVMCIRuntime.java:294)
        at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.<init>(HotSpotJVMCIRuntime.java:70)
        at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime$DelayedInit.<clinit>(HotSpotJVMCIRuntime.java:78)
        at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.runtime(HotSpotJVMCIRuntime.java:94)
        at jdk.vm.ci.runtime.JVMCI.initializeRuntime(Native Method)
        at jdk.vm.ci.runtime.JVMCI.<clinit>(JVMCI.java:60)
Caused by: java.lang.IllegalArgumentException: Could not find option class.analysis
        at org.graalvm.compiler.options.OptionsParser.parseOption(OptionsParser.java:134)
        at org.graalvm.compiler.options.OptionsParser.parseOptions(OptionsParser.java:76)
        at org.graalvm.compiler.hotspot.HotSpotGraalOptionValues.initializeOptions(HotSpotGraalOptionValues.java:129)
        at org.graalvm.compiler.hotspot.HotSpotGraalOptionValues.<clinit>(HotSpotGraalOptionValues.java:74)
        at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.onSelection(HotSpotGraalCompilerFactory.java:74)
        at jdk.vm.ci.hotspot.HotSpotJVMCICompilerConfig.getCompilerFactory(HotSpotJVMCICompilerConfig.java:128)
        at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.<init>(HotSpotJVMCIRuntime.java:294)
        at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.<init>(HotSpotJVMCIRuntime.java:70)
        at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime$DelayedInit.<clinit>(HotSpotJVMCIRuntime.java:78)
        at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.runtime(HotSpotJVMCIRuntime.java:94)
        at jdk.vm.ci.runtime.JVMCI.initializeRuntime(Native Method)
        at jdk.vm.ci.runtime.JVMCI.<clinit>(JVMCI.java:60)
```

It seems that a system property starting with `graal` is expected to be a valid GraalVM option

**Comment by jonbettinger** [comment]
You can generate the reflect.json with this:
`java -cp build/libs/hello-world-java-0.1-all.jar io.micronaut.graal.reflect.GraalClassLoadingAnalyzer`
After that, the native build worked, but core dumped trying to run `./hw`

I had better luck with hello-world-function.
`java -cp build/libs/hello-world-function-0.1-all.jar io.micronaut.graal.reflect.GraalClassLoadingAnalyzer` worked. 
The `build-native-image.sh` script expects reflect.json in the wrong directory, but it does build and run after fixing that.
